### ISSUE TITLE
 Cannot split a chunk that has already been edited

### ISSUE THREAD

**Issue by liwenfengg** [unocss-applet/unocss-applet#1]
![image](https://user-images.githubusercontent.com/40257198/184807856-19a36334-7a0c-4811-846d-b2383b805096.png)

**Comment by liwenfengg** [comment]
If you comment out `transformerRenameClass`, you will not report an error, but the style will not take effect.

**Comment by liwenfengg** [comment]
![image](https://user-images.githubusercontent.com/40257198/184809220-af6d3af6-679b-44cf-b296-c963690048d9.png)
This is the index.html of the project generated by uni-app cli.

**Comment by zguolee** [comment]
I created a project with the `npx degit dcloudio/uni-preset-vue#vite-ts uni-vue3` command. and didn't encounter this. Could you provide a repo?

**Comment by liwenfengg** [comment]
I found that it has something to do with the order of `transformerVariantGroup` and `transformerRenameClass` in `transformers`.

![image](https://user-images.githubusercontent.com/40257198/184846156-cdae854e-05c6-4bf4-9854-a5ab8f35a3a4.png)

[demo-repo](https://github.com/liwenfengg/cloudio-uni-preset-vue-vite-ts-unocss-applet)

This is the demo repo, you can have a try.

**Comment by liwenfengg** [comment]
Why so many known and unknown?

![image](https://user-images.githubusercontent.com/40257198/184848275-3ad1ae86-c5df-47f8-bc3f-e60c99f76cc9.png)

**Comment by zguolee** [comment]
> Why so many known and unknown?
> 

I have deleted the log in the new version, only need to update the next version.

**Comment by liwenfengg** [comment]
> > Why so many known and unknown?
> 
> I have deleted the log in the new version, only need to update the next version.

Ooh, okay.

**Comment by zguolee** [comment]
> I found that it has something to do with the order of `transformerVariantGroup` and `transformerRenameClass` in `transformers`.
> 
> ![image](https://user-images.githubusercontent.com/40257198/184846156-cdae854e-05c6-4bf4-9854-a5ab8f35a3a4.png)
> 
> [demo-repo](https://github.com/liwenfengg/cloudio-uni-preset-vue-vite-ts-unocss-applet)
> 
> This is the demo repo, you can have a try.

Yes, I don't know if I can solve this problem, I will try it later.

**Comment by liwenfengg** [comment]
![image](https://user-images.githubusercontent.com/40257198/184852030-d9b6be88-aac9-41a6-b691-4ee869b8e3d4.png)
Another question.
Use `uni-easyinput` in `uni-ui` to report this error.
(not when using `presetUni`)

**Comment by liwenfengg** [comment]
[demo repo](https://github.com/liwenfengg/cloudio-uni-preset-vue-vite-ts-unocss-applet)

**Comment by liwenfengg** [comment]
> ![image](https://user-images.githubusercontent.com/40257198/184852030-d9b6be88-aac9-41a6-b691-4ee869b8e3d4.png) Another question. Use `uni-easyinput` in `uni-ui` to report this error. (not when using `presetUni`)

[demo repo](https://github.com/liwenfengg/cloudio-uni-preset-vue-vite-ts-unocss-applet)

**Comment by zguolee** [comment]
> I found that it has something to do with the order of `transformerVariantGroup` and `transformerRenameClass` in `transformers`.
> 
> ![image](https://user-images.githubusercontent.com/40257198/184846156-cdae854e-05c6-4bf4-9854-a5ab8f35a3a4.png)
> 
> [demo-repo](https://github.com/liwenfengg/cloudio-uni-preset-vue-vite-ts-unocss-applet)
> 
> This is the demo repo, you can have a try.

Now `transformerVariantGroup` supports `transformerRenameClass` default, you don’t need to introduce `transformerRenameClass`.
