### ISSUE TITLE
unocss 升级到 0.47.0 之后的版本，uniapp 编译到 app-Android 端后 unocss 的样式无效

### ISSUE THREAD

**Issue by jacksonyu** [unocss-applet/unocss-applet#10]
使用 https://github.com/zguolee/starter-uni 初始化项目，升级 unocss 到 0.47.0 后，编译到 uniapp 安卓端，unocss 样式失效。

**Comment by zguolee** [comment]
`unocss-applet` 无法处理这个问题。

**Comment by jacksonyu** [comment]
> `unocss-applet` 无法处理这个问题，相关[dcloudio/uni-app#4061 (comment)](https://github.com/dcloudio/uni-app/issues/4061#issuecomment-1354333499)，[unocss/unocss#1999 (comment)](https://github.com/unocss/unocss/issues/1999#issuecomment-1352659481)。

谢谢提醒

**Comment by StrivingRabbit** [comment]
暂时先用 0.46.x 吧，后续看看怎么优化一下
