### ISSUE TITLE
Failed to parse bg-blue TypeError: e.replace is not a function.

### ISSUE THREAD

**Issue by dahvlhldle** [unocss-applet/unocss-applet#12]
背景色出错

**Comment by zguolee** [comment]
具体是怎么出错，有复现仓库吗？

**Comment by dahvlhldle** [comment]
是vscode 报错。 用的插件是UnoCSS for VS Code。vscode 代码无法识别，但是可以正常显示。但是当设置颜色未grey或者black1，编译后class标签就消失了。


`"unocss": "^0.46.5",
   uniapp:3.0.0-3061820230117001
`

**Comment by zguolee** [comment]
- VS Code 不显示可能需要设置一下插件的 root 路径`"unocss.root": "xxx"`
- [`grey`](https://uno.antfu.me/?s=bg-grey) 和 [`black1`](https://uno.antfu.me/?s=bg-black1) UnoCSS 没有这个正则匹配，需要在`unocss.config`设置主题颜色值。
```ts
export default defineConfig({
  theme: {
    colors: {
      grey: '#xxx',
      black: '#xxx',
    },
  },
})
```

**Comment by dahvlhldle** [comment]
感谢！回复！可以解决。
我升级到v0.49 ，样式就丢失了。尝试了多个版本，发现只有0.46才行。这个只有等官方修复么？

**Comment by zguolee** [comment]
可以看一下这个[issue](https://github.com/unocss-applet/unocss-applet/issues/10)，前一段这个问题已经修复了，检查一下 `uniapp` 和 `vite` 相关版本是不是最新的。
当然，新版本会有一些🚨breakchange，比如 `border` 之前会生成 `style` 和 `width`，现在只有 `width`，这就需要自己去改了。

**Comment by dahvlhldle** [comment]
vite 太旧了 。解决了。感谢！
