### ISSUE TITLE
uniapp 编译成H5的情况下，@apply指令内的rpx单位无法转换

### ISSUE THREAD

**Issue by q807175022** [unocss-applet/unocss-applet#13]
使用 class ，在 h5 环境下，rpx 可以转换成 rem

![image](https://user-images.githubusercontent.com/34495095/218972377-7dcb69e0-f4b0-4c44-a531-471b450d8912.png)

使用 @apply 生成的css，没有转换成 rem

<template>
  <view class="flex justify-center items-center">
    <view class="w-100rpx h-100rpx bg-red mb-40rpx" />

    <view class="uno-class"></view>
  </view>
</template>

<style>
.uno-class{
  @apply w-200rpx h-200rpx bg-blue;
}
</style>

![image](https://user-images.githubusercontent.com/34495095/218972432-33e7d71f-05f4-4306-9e78-c65cfc20eeb9.png)

**Comment by q807175022** [comment]
你好，这里我看你好像是让我改成根据uniapp的运行环境判断是否启用 `presetRemToRpx` ，但是如果H5不启用的话，是否代表我需要为这个uniapp项目的H5端重新写一套新的样式？
因为我设置了`presetRemToRpx({ enable: true, baseFontSize: 4, screenWidth: 750 })`,想让类名的数值1：1转换为rpx;

**Comment by zguolee** [comment]
对于`presetRemToRpx`，如果是开启状态（小程序环境）执行`Rem to Rpx`，否则（H5）执行`Rpx to Rem`，不需要重写样式。

```
const isApplet = process.env?.UNI_PLATFORM?.startsWith('mp')
...
presetRemToRpx({ enable: isApplet }),
...
```

**Comment by q807175022** [comment]
那我测试时好像关闭后，baseFontSize: 4, screenWidth: 750 这个设置的比例不起效果了

**Comment by zguolee** [comment]
我去测试了下开启后`1rem`=>`(1*4)*(750/750)=4rpx`，关闭后`1rpx`=>`1/(750/750)/4=0.25rem`。

**Comment by zguolee** [comment]
现在我们增加了一个新的`preset-rpx-to-rem`，可以按需使用。 
```
isApplet ? presetRemToRpx() : presetRpxToRem(),
```

**Comment by q807175022** [comment]
感谢，我在你刚刚上传的在"unocss-applet": "^0.3.1" 这个版本中找到presetRemRpx，在H5端对rpx已经能转换为rem了，但是好像没有按照设置的规则比例转换

**Comment by zguolee** [comment]
可以给一个你设置转换的错误结果例子吗😂

**Comment by q807175022** [comment]
![image](https://user-images.githubusercontent.com/34495095/219994458-33332a86-4ea2-483d-90d0-1948a7719516.png)
H5的效果：
![image](https://user-images.githubusercontent.com/34495095/219994695-cb966905-9e9d-436f-bf7e-6d962a0c3217.png)
小程序：
![image](https://user-images.githubusercontent.com/34495095/219994753-f1ef0b41-af05-4c69-9515-3c72886dd8b9.png)

**Comment by zguolee** [comment]
这个不是本插件的问题，`UnoCSS` 默认`rootFontSize`为 16px，同样的浏览器和小程序也是`16px`。`UnoCSS`首先会以16px将 `w-40`会生成`width: 10rem`。`remRpx` 插件里设置了`2px`，对于小程序来说是先转换为 `px`再转换为 `rpx`，最终`w-40` 生成 `width: 40rpx`，这没有问题。但是在H5场景下，`rootFontSize`还是以16px，那么10rem即为 160px，所以在H5场景下需要手动设置相应的`rootFontSize`，这里为 `2px` 这样`10rem`才为`20px`。
