### ISSUE TITLE
早上更新了以下依赖，原来的代码全都炸了

### ISSUE THREAD

**Issue by mowtwo** [unocss-applet/unocss-applet#14]
![image](https://user-images.githubusercontent.com/41664636/220253157-3a6e72b6-7d5c-46f0-bfaf-da58d48e61b9.png)
![image](https://user-images.githubusercontent.com/41664636/220253232-d9d972ad-0b78-4f55-9d49-c282cfe451ea.png)

**Comment by zguolee** [comment]
更新了哪几个依赖，第二个图看起来版本也是之前的。

**Comment by mowtwo** [comment]
> 更新了哪几个依赖，第二个图看起来版本也是之前的。

你这句话提醒我了，我刚刚查看了下lock里的unocss-applet的版本是0.2.22，我回退到了0.2.21恢复正常了😂，希望可以帮忙排查下

**Comment by zguolee** [comment]
或许你可以使用这个[工具](https://github.com/antfu/taze)更新一下所有的依赖。

**Comment by mowtwo** [comment]
> 或许你可以使用这个[工具](https://github.com/antfu/taze)更新一下所有的依赖。

好的，我先尝试通过这个更新，我之前是通过pnpm update做了简单的更新，然后出现了问题，而且我发现出现问题的文件都是之前使用过unocss 的vue文件，没使用过的文件没有受到影响，不清楚具体造成影响的原因

**Comment by zguolee** [comment]
> > 或许你可以使用这个[工具](https://github.com/antfu/taze)更新一下所有的依赖。
> 
> 好的，我先尝试通过这个更新，我之前是通过pnpm update做了简单的更新，然后出现了问题，而且我发现出现问题的文件都是之前使用过unocss 的vue文件，没使用过的文件没有受到影响，不清楚具体造成影响的原因

如果更新依赖解决了问题，请关闭issue。
