### ISSUE TITLE
before:content-[...] 是否支持?

### ISSUE THREAD

**Issue by hootigger** [unocss-applet/unocss-applet#20]
我不是主做web前端的,Unocss playground 支持 

```
//  before:content
<div class="bg-green-500 text-2xl text-gray-500/90 w-40 h-10 before:content-['test']"></div>
```
但是插件处理生成小程序代码的时候, 貌似会移除 content 声明, 导致无法使用 是功能没有支持?还是bug?

![image](https://github.com/unocss-applet/unocss-applet/assets/23418191/1d3e99ad-cd8c-44ba-bf62-a12ffcd52745)

使用 tailwindcss测试发现 https://github.com/sonofmagic/weapp-tailwindcss-webpack-plugin 这个库是可以正常处理的.

**Comment by hootigger** [comment]
我web前端知识太少了 我是做iOS开发的.

**Comment by zguolee** [comment]
处理时是有问题，是一个BUG

**Comment by zguolee** [comment]
> 还发现那些 任意值的写法貌似处理到 小程序也会有问题
> 
> ```
> <div class="w-20 h-[20px] bg-red-500/80"></div>
> ```

这个我试了下没有问题

**Comment by zguolee** [comment]
> 我刚看了下demo，好像是这个导致的。
> 
> ```
> // 是这个 生成的css 带 >:not() 貌似小程序  不支持 
> class="space-y-[10px]"
> // =>  .space-y-_a_10px_a_>:not([hidden])~:not([hidden])>:not([hidden])~:not([hidden]){--un-space-y-reverse:0;margin-top:calc(10px * calc(1 - var(--un-space-y-reverse)));margin-bottom:calc(10px * var(--un-space-y-reverse));}.
> ```
> 
> 我又看了下其它库， 有的处理成这样了
> 
> ```
> .space-y-_lfl_10px_lfr_>view+view,
> .space-y-_lfl_10px_lfr_>button+button,
> .space-y-_lfl_10px_lfr_>text+text,
> .space-y-_lfl_10px_lfr_>image+image,
> .space-y-_lfl_10px_lfr_>uni-view+uni-view,
> .space-y-_lfl_10px_lfr_>uni-button+uni-button,
> .space-y-_lfl_10px_lfr_>uni-text+uni-text,
> .space-y-_lfl_10px_lfr_>uni-image+uni-image,
> .space-y-_lfl_10px_lfr_>taro-view-core+taro-view-core,
> .space-y-_lfl_10px_lfr_>taro-image-core+taro-image-core,
> .space-y-_lfl_10px_lfr_>taro-text-core+taro-text-core,
> .space-y-_lfl_10px_lfr_>taro-button-core+taro-button-core {
>     --un-space-y-reverse: 0;
>     margin-top: calc(10px * calc(1 - var(--un-space-y-reverse)));
>     margin-bottom: calc(10px * var(--un-space-y-reverse));
> }
> ```

是的 `/^space-?([xy])-?(-?.+)$/`、`/^space-?([xy])-reverse$/` 和 `/^divide-(.+)$/` 暂时都不支持，可以新开一个 issue。

**Comment by hootigger** [comment]
感谢你快速修复了 before:content-[xx]  ，刚才测试下来很奇怪，我update了0.4.12 重新build发现 依然没有处理成功，但是直接clone本项目，运行 playground直接测试 发现可以。。很神奇。不知道是哪里我接错了，我明天有时间再看下吧.

```
// unocss.config
直接复制的本仓库的readme
// 原始语句
<view class="space-y-[10px] bg-red-500/80 w-10 h-20 before:content-['testtest']"></view>
// 生成的wxml
<view class="space-y-_a_10px_a_ bg-red-500_a_80 w-10 h-20 before:content-['testtest']"></view>

//vite
import { defineConfig } from "vite";
import uni from "@dcloudio/vite-plugin-uni";
import commonjs from '@rollup/plugin-commonjs'
import UnoCSS from 'unocss/vite'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [uni(), commonjs(),UnoCSS()],
});

```

**Comment by hootigger** [comment]
![image](https://github.com/unocss-applet/unocss-applet/assets/23418191/fac921a9-b3e2-4dc5-84ca-337e50b66810)
我测试了下好像和仓库没关系,是unocss没解析好?对于我这种不是web前端的来说,排查这个太坑了. 我自己去研究吧

**Comment by hootigger** [comment]
@zguolee 我测试发现了问题所在, 
![image](https://github.com/unocss-applet/unocss-applet/assets/23418191/85ec9258-912c-4e98-b867-bae9308fbb29)

我项目中的unocss默认是最新 0.51.13 我发现unocss-applet依赖的是0.50.6 (我项目里看到是依赖0.50.8)当我把项目配置成0.50.8 输出就可以看到解析出了 content.  应该和
![image](https://github.com/unocss-applet/unocss-applet/assets/23418191/9e95a1db-5b38-4b35-8576-bcd02c55cff3)
这里有关系,版本不匹配造成的. 你可以测试100%复现,只有和你版本一样才能正常

**Comment by zguolee** [comment]
是否可以提供一下最小复现仓库，我这里并没有问题🥲

**Comment by hootigger** [comment]
@zguolee 不好意思, 属实是我的问题,pnpm导致的, 我新建的项目 上面提到版本都是一样的,测试下来,功能正常, 可是我那个项目是错误,估计npm不会有这样问题,pnpm链接导致的(可能和我频繁测试插件导致项目依赖太乱)我删掉pnpm-lock.yaml 重新install正常了. 再次感谢. 此issue可以close了

**Comment by hootigger** [comment]
![image](https://github.com/unocss-applet/unocss-applet/assets/23418191/20409510-9af3-4132-9a97-06404d9b1c8e)
![image](https://github.com/unocss-applet/unocss-applet/assets/23418191/a6ee94bc-dd78-4b19-991e-07be15a829f1)

**Comment by zguolee** [comment]
如果使用 `pnpm`，可以在项目根目录创建一个 `.npmrc` 文件，内容为
```
shamefully-hoist = true
```

**Comment by hootigger** [comment]
好的,谢谢
