### ISSUE TITLE
content-['中文'] 转换小程序异常

### ISSUE THREAD

**Issue by hootigger** [unocss-applet/unocss-applet#22]
```
before:content-['你好中国'] 
=> 
{
  selector: '.before_a_content-_a__a_你好中国_a__a_::before',
  entries: [ [ 'content', "'你好中国'" ] ],
  parent: undefined,
  layer: undefined,
  sort: undefined,
  noMerge: undefined
}
```
小程序wxss会报错
![image](https://github.com/unocss-applet/unocss-applet/assets/23418191/a5d22c09-cf9d-49e7-ade7-db494299b848)
是不是可以对选择器名称出现中文就替换成随机字符串?这样是不是就兼容了小程序?

**Comment by hootigger** [comment]
我尝试在postprocess中处理中文,encode并去除%, 发现生成的wxss处理了,但是wxml却没有处理, 对Unocss插件执行原理不是很了解.

**Comment by zguolee** [comment]
> 我尝试在postprocess中处理中文,encode并去除%, 发现生成的wxss处理了,但是wxml却没有处理, 对Unocss插件执行原理不是很了解.

wxml 需要使用 unocss 的 transformer 处理，我已经在解决 issue，还有一个小问题需要处理下。

**Comment by hootigger** [comment]
原来这样啊,了解.

**Comment by zguolee** [comment]
已经在 https://github.com/unocss-applet/unocss-applet/pull/23 中修复，但是对于 包含$$字符的content 还没有好的方式处理。
