### ISSUE TITLE
can't use 'space-xxx'

### ISSUE THREAD

**Issue by transtone** [unocss-applet/unocss-applet#25]
https://github.com/unocss-applet/unocss-applet/issues/21 这里说已经支持 'space-xxx' 的写法了，而且这里有对应的示例：
https://github.com/unocss-applet/unocss-applet/blob/main/playgrounds/uni-app/src/pages/index/index.vue#L71

但，经微信小程序实测，该用法无效。我把 playgrounds/unapp 示例环境单独拿出来了：
https://github.com/transtone/unocss-applet-preset

复现方法：`yarn && yarn dev:mp-weixin`
开发环境：windows11-22H2/node-v18.15.0

编译后的 app.wxss 文件中，出现了 `page,::before,::after` 这样的代码。
https://github.com/transtone/unocss-applet-preset/-blob/main/app.wxss

**Comment by transtone** [comment]
@zguolee 你又骗我。
![image](https://github.com/unocss-applet/unocss-applet/assets/46688/aa7b7103-bb7b-4149-8105-296a1e9812c1)

**Comment by zguolee** [comment]
::before 这个不想要可以设置 {preflight: false}
