### ISSUE TITLE
WeChat Applet html content Be analyzed

### ISSUE THREAD

**Issue by Ares-Chang** [unocss-applet/unocss-applet#27]
我在 html 内容中写入 unocss class 被错误解析并写入。

这是我的 html 内容:

![image](https://github.com/unocss-applet/unocss-applet/assets/36911513/be260c54-721f-474a-ad88-6e6b269427ba)

然后在微信小程序端被进行解析，h5 方面没有这个问题。

`w-2.5rem` 被解析成了 `w-2_a_5rem` ，但是我并未使用这个 class，我理解是在解析的时候是不是做了全局的筛选，并没有只筛选属性和 class。

![image](https://github.com/unocss-applet/unocss-applet/assets/36911513/83e61e56-4a4e-46b3-851d-33e076315b70)

**Comment by zguolee** [comment]
因为这个匹配也是使用 unocss 来解析，可以看到 `w-2.5rem` 下面有虚线。可以[查看](https://unocss.dev/guide/extracting#extracting-from-build-tools-pipeline)来获得更多支持。
```
<!-- @unocss-skip-start -->
<!-- `text-red` will not be extracted -->
<p class="text-red">
  Red
</p>
<!-- @unocss-skip-end -->
```

**Comment by Ares-Chang** [comment]
我理解，这个插件是通过 unocss 暴露出来的接口来进行解析的，因为 web 端不牵扯选择器无法使用问题，所以不需要进行符号转译。但是运行到小程序等非标准平台上就出现问题了。

但是它不应该抽离出属性写到 class 里嘛？为什么会改变我的原内容。

**Comment by zguolee** [comment]
因为 `w-2.5rem` 是一个合法的 token，尽管是 DOM 元素的内容。插件在处理小程序端时，对于不支持的合法 token 都会进行转换，并没有只处理 DOM 元素的属性。

**Comment by Ares-Chang** [comment]
好的，了解。

Thanks
