### ISSUE TITLE
使用transformerDirectives报错 会多生成一个 ;

### ISSUE THREAD

**Issue by LeoKun1231** [unocss-applet/unocss-applet#30]
使用@apply功能报错，每次微信端都会多生成一个分号，h5没有。
![image](https://github.com/unocss-applet/unocss-applet/assets/88810970/e1e3e2c3-d742-4848-ab9a-6ce531a77d17)
![image](https://github.com/unocss-applet/unocss-applet/assets/88810970/0f32bfd6-78b6-4fea-8e5f-d81d930b2560)

**Comment by zguolee** [comment]
删除分号就好了，这个是 uni-app 对这个规则做了处理，插件并没有处理 transformerDirectives 的 token，暂时没有处理这个问题的计划。https://github.com/unocss-applet/unocss-applet/issues/26#issuecomment-1601021645
