### ISSUE TITLE
main.ts中的uno.css是从哪儿来的呢

### ISSUE THREAD

**Issue by zxfd** [unocss-applet/unocss-applet#31]
没有找到相关依赖，src下面也没找到相关自定义文件

**Comment by zguolee** [comment]
可以先参考 [UnoCSS](https://unocss.dev/integrations/vite) 配置一下。

**Comment by zxfd** [comment]
官方文档里面使用的是虚拟模块`import 'virtual:uno.css'`

**Comment by zguolee** [comment]
#32
