### ISSUE TITLE
`transformerAttributify` not work for tarojs

### ISSUE THREAD

**Issue by qianlanse** [unocss-applet/unocss-applet#34]
请问transformerDirectives和transformerVariantGroup转换器怎么在小程序中不起作用，用的taro框架编译
![WX20231011-152555](https://github.com/unocss-applet/unocss-applet/assets/13144533/fd9941a5-67a6-4691-a8d5-ae36d3adb756)
![WX20231011-152847](https://github.com/unocss-applet/unocss-applet/assets/13144533/cbd2cc73-6297-4fba-b6b4-8d9d0dc522b4)
![WX20231011-152909](https://github.com/unocss-applet/unocss-applet/assets/13144533/32d1ec71-62aa-46e5-9c04-cbc888c79b6d)

**Comment by zguolee** [comment]
我看到第二个图片这里没有用`@apply`和 `hover:(xxx xx)`类似的语法。

**Comment by qianlanse** [comment]
> 我看到第二个图片这里没有用`@apply`和 `hover:(xxx xx)`类似的语法。

可以看数字的样式是没有的

**Comment by zguolee** [comment]
> > 我看到第二个图片这里没有用`@apply`和 `hover:(xxx xx)`类似的语法。
> 
> 可以看数字的样式是没有的

这个是属性模式，@unocss-applet/transformer-attributify

**Comment by zguolee** [comment]
暂时还没有修复，不知道哪里出了问题，看到template也是转换了的。
