### ISSUE TITLE
in app side, `shortcuts` and `Attributify Mode` Still not supported

### ISSUE THREAD

**Issue by liwenfengg** [unocss-applet/unocss-applet#4]
in app side, `shortcuts` and `Attributify Mode` Still not supported

`text="base #F2FF"`

[attributify-mode](https://github.com/unocss/unocss/tree/main/packages/preset-attributify/#attributify-mode)

![image](https://user-images.githubusercontent.com/40257198/185310325-614d1af2-f686-4470-ac66-861f8971acbd.png)

_Originally posted by @liwenfengg in https://github.com/unocss-applet/unocss-applet/issues/3#issuecomment-1219093922_

**Comment by liwenfengg** [comment]
Today, when testing, I found that only custom attributes (such as custom colors) don't take effect on the app side.

![image](https://user-images.githubusercontent.com/40257198/185557809-be7080e6-6293-4a22-8b39-293a2cc6891c.png)

**Comment by zguolee** [comment]
`Attributify Mode` is already supported, but `uni-ui` is temporarily unavailable.

**Comment by zguolee** [comment]
Sorry, `Attributify Mode` still has issues.😅😅

**Comment by zguolee** [comment]
It should have been fixed. You can refer to the latest documents to reconfigure it.

**Comment by liwenfengg** [comment]
> It should have been fixed. You can refer to the latest documents to reconfigure it.

Thank you. I'll try it later
