### ISSUE TITLE
存在需要 unicode 转义的类名时，生成样式不能正常运行在小程序上

### ISSUE THREAD

**Issue by ModyQyW** [unocss-applet/unocss-applet#46]
https://unocss.dev/play/?html=DwEwlgbgBAxgNgQwM5ILwCIBMAPOAuAJwHsBXAOxAFMQBaHOdAPmAHpwJGAoIA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCqWEcAvnOlBCHAOQCujAYypVuAKFCRYicpRowAgmDAAbWizYcufQcIC0AQyWqYY0agAek%2BGnT7ey6xmx4CxABQJRcGdVpUAXHAA2l7ecAD04T5yDBBuAJQkod4UvgpGtAlJ3gC6SczxokA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmjpAA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwBpxp5k0AJMVHTbPIkCfOAByXgEsA3fO3AgF8gA

<img width="1512" alt="image" src="https://github.com/unocss-applet/unocss-applet/assets/31850793/9c003b06-bc5d-49c2-a437-c0fe7eba7877">

与 https://github.com/uni-helper/vite-plugin-uni-tailwind/issues/32 类似

**Comment by zguolee** [comment]
> 从生成的 CSS 存在 `_a_` 来看，应该是支持的

这个例子是支持的，`xl:!bg-teal` 多了 `!` 会变成
<img width="438" alt="image" src="https://github.com/unocss-applet/unocss-applet/assets/40738594/17c7a64d-3f28-4b78-84b0-e72c003d4a6c">
<img width="455" alt="image" src="https://github.com/unocss-applet/unocss-applet/assets/40738594/ff99c5e1-14ee-4ff5-9f04-2347ba3a6359">

**Comment by zguolee** [comment]
fix
