### ISSUE TITLE
[plugin:vite:vue] Illegal '/' in tags.

### ISSUE THREAD

**Issue by liwenfengg** [unocss-applet/unocss-applet#5]
#4 

![image](https://user-images.githubusercontent.com/40257198/187124755-3fb2052d-4643-45a9-9af9-04ba5868d46b.png)

When I did what you said, I sent a new error on the app side.

This is the [demo repo](https://github.com/liwenfengg/cloudio-uni-preset-vue-vite-ts-unocss-applet), you can have a try.

**Comment by liwenfengg** [comment]
The project I created using your template [starter-uni](https://github.com/zguolee/starter-uni) also has this problem, and I only added this line.

`<div i-carbon-campsite inline-block color="blue" />`

This is the [demo repo](https://github.com/liwenfengg/starter-uni-unocss-applet), you can have a try.

**Comment by liwenfengg** [comment]
![image](https://user-images.githubusercontent.com/40257198/187137796-2b3310f8-4fd5-4517-b38b-b0b77c7b2f51.png)

**Comment by LLinVIP** [comment]
> 
I also noticed this question. When I use old unocss-preset-uni, I didn't encounter this question.

**Comment by zguolee** [comment]
Because `unocss-applet` and `unocss-preset-uni` use two different ways to convert. It has been fixed now.

**Comment by zguolee** [comment]
> #4 
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/40257198/187124755-3fb2052d-4643-45a9-9af9-04ba5868d46b.png)
> 
> 
> 
> When I did what you said, I sent a new error on the app side.
> 
> 
> 
> This is the [demo repo](https://github.com/liwenfengg/cloudio-uni-preset-vue-vite-ts-unocss-applet), you can have a try.

Here's another problem, this plugin modifies the content of the tags(e.g. class=""). I will fix it soon.

**Comment by liwenfengg** [comment]
> > #4
> > ![image](https://user-images.githubusercontent.com/40257198/187124755-3fb2052d-4643-45a9-9af9-04ba5868d46b.png)
> > When I did what you said, I sent a new error on the app side.
> > This is the [demo repo](https://github.com/liwenfengg/cloudio-uni-preset-vue-vite-ts-unocss-applet), you can have a try.
> 
> Here's another problem, this plugin modifies the content of the tags(e.g. class=""). I will fix it soon.

I'll wait.  and test it once you're done.

**Comment by zguolee** [comment]
> > > #4
> > > ![image](https://user-images.githubusercontent.com/40257198/187124755-3fb2052d-4643-45a9-9af9-04ba5868d46b.png)
> > > When I did what you said, I sent a new error on the app side.
> > > This is the [demo repo](https://github.com/liwenfengg/cloudio-uni-preset-vue-vite-ts-unocss-applet), you can have a try.
> > 
> > 
> > Here's another problem, this plugin modifies the content of the tags(e.g. class=""). I will fix it soon.
> 
> I'll wait. and test it once you're done.


It has been solved in v0.2.4, but if the string contains it, it cannot be solved for the time being(e.g 'p-2.5').

**Comment by liwenfengg** [comment]
> > > > #4
> > > > ![image](https://user-images.githubusercontent.com/40257198/187124755-3fb2052d-4643-45a9-9af9-04ba5868d46b.png)
> > > > When I did what you said, I sent a new error on the app side.
> > > > This is the [demo repo](https://github.com/liwenfengg/cloudio-uni-preset-vue-vite-ts-unocss-applet), you can have a try.
> > > 
> > > 
> > > Here's another problem, this plugin modifies the content of the tags(e.g. class=""). I will fix it soon.
> > 
> > 
> > I'll wait. and test it once you're done.
> 
> It has been solved in v0.2.4, but if the string contains it, it cannot be solved for the time being(e.g 'p-2.5').

contains what?  `/` ?

**Comment by zguolee** [comment]
> 

No, including the `UnoCSS` rules, there are special characters(`[.:%!#()[\/\],]`) at the same time.

```html
// from
<div>{{ 'bg-[hsl(2.7,81.9%,69.6%)]' }}</div>

// to
<div>{{ 'uno-98db2v' }}</div>
```

**Comment by liwenfengg** [comment]
> > 
> 
> No, including the `UnoCSS` rules, there are special characters(`[.:%!#()[\/\],]`) at the same time.
> 
> ```
> // from
> <div>{{ 'bg-[hsl(2.7,81.9%,69.6%)]' }}</div>
> 
> // to
> <div>{{ 'uno-98db2v' }}</div>
> ```

![image](https://user-images.githubusercontent.com/40257198/187636549-19706df7-e292-4c61-ab45-552cfa1dabc3.png)

hhh, Does it convert everything?(doge

**Comment by zguolee** [comment]
Yes, only strings(UnoCSS rules), normal strings will not be converted. But the impact is not very large, and there is almost no literal scene🤣. Strings in `<template></template>` may be resolved in the future.

**Comment by circle33** [comment]
I solved the problem
![image](https://github.com/unocss-applet/unocss-applet/assets/100536623/964b70c2-d10c-4ba1-8e5d-fc5e16d1433f)
