### ISSUE TITLE
颜色规则没有提示:color-#0f90f9 在vscode里的unocss插件

### ISSUE THREAD

**Issue by xjt13417680505** [unocss-applet/unocss-applet#56]
在vscode里的unocss插件 如class="color-#0f90f9"的颜色规则没有提示;
![image](https://github.com/unocss-applet/unocss-applet/assets/75859003/25048d32-c84e-4b7a-bb48-77a9cfc071f0)
改用 presetUno()就有了
![image](https://github.com/unocss-applet/unocss-applet/assets/75859003/7edbeff6-87f0-4f57-8bc6-a803089940bd)

**Comment by zguolee** [comment]
看一下uno.config.ts配置

**Comment by xjt13417680505** [comment]
> 看一下uno.config.ts配置

// uno.config.ts
import {
  Preset,
  defineConfig,
  presetAttributify,
  presetIcons,
  transformerDirectives,
  transformerVariantGroup,
} from 'unocss'

import {
  presetApplet,
  presetRemRpx,
  transformerApplet,
  transformerAttributify,
} from 'unocss-applet'

// @see https://unocss.dev/presets/legacy-compat
import presetLegacyCompat from '@unocss/preset-legacy-compat'

const isEditor = process.env?.UNI_PLATFORM === void 0
const isH5 = process.env?.UNI_PLATFORM === 'h5'
const isMp = process.env?.UNI_PLATFORM?.startsWith('mp') ?? false

const presets: Preset[] = []
if (!isMp) {
  /**
   * you can add `presetAttributify()` here to enable unocss attributify mode prompt
   * although preset is not working for applet, but will generate useless css
   * 为了不生产无用的css,要过滤掉 applet
   */
  // 支持css class属性化，eg: `<button bg="blue-400 hover:blue-500 dark:blue-500 dark:hover:blue-600" text="sm white">attributify Button</button>`
  presets.push(presetAttributify())
}
if (!isH5) {
  presets.push(presetRemRpx())
}
export default defineConfig({
  presets: [
    presetApplet({ enable: !isH5 }),
    ...presets,
    // 支持图标，需要搭配图标库，eg: @iconify-json/carbon, 使用 `<button class="i-carbon-sun dark:i-carbon-moon" />`
    presetIcons({
      scale: 1.2,
      warn: true,
      extraProperties: {
        display: 'inline-block',
        'vertical-align': 'middle',
      },
    }),
    // 将颜色函数 (rgb()和hsl()) 从空格分隔转换为逗号分隔，更好的兼容性app端，example：
    // `rgb(255 0 0)` -> `rgb(255, 0, 0)`
    // `rgba(255 0 0 / 0.5)` -> `rgba(255, 0, 0, 0.5)`
    presetLegacyCompat({
      commaStyleColorFunction: true,
    }) as Preset,
  ],
  /**
   * 自定义快捷语句
   * @see https://github.com/unocss/unocss#shortcuts
   */
  shortcuts: [['center', 'flex justify-center items-center']],
  transformers: [
    // 启用 @apply 功能
    transformerDirectives(),
    // 启用 () 分组功能
    // 支持css class组合，eg: `<div class="hover:(bg-gray-400 font-medium) font-(light mono)">测试 unocss</div>`
    transformerVariantGroup(),
    // Don't change the following order
    transformerAttributify({
      // 解决与第三方框架样式冲突问题
      prefixedOnly: true,
      prefix: 'fg',
    }),
    transformerApplet(),
  ],
  rules: [
    [
      'p-safe',
      {
        padding:
          'env(safe-area-inset-top) env(safe-area-inset-right) env(safe-area-inset-bottom) env(safe-area-inset-left)',
      },
    ],
    ['pt-safe', { 'padding-top': 'env(safe-area-inset-top)' }],
    ['pb-safe', { 'padding-bottom': 'env(safe-area-inset-bottom)' }],
  ],
})

/**
 * 最终这一套组合下来会得到：
 * mp 里面：mt-4 => margin-top: 32rpx
 * h5 里面：mt-4 => margin-top: 1rem
 */

**Comment by zguolee** [comment]
看你的配置默认isH5可能为undefined，导致presetApplet被启用，所以vscode中只会匹配到转义后的，建议使用文档的配置方式。

**Comment by xjt13417680505** [comment]
> 看你的配置默认isH5可能为undefined，导致presetApplet被启用，所以vscode中只会匹配到转义后的，建议使用文档的配置方式。

isH5直接赋值true或false也没有提示；
复制文档uno.config.ts示例也是不行的(示例缺少presetAttributify的导入)；

**Comment by xjt13417680505** [comment]
解决了
![image](https://github.com/unocss-applet/unocss-applet/assets/75859003/81dddc51-23f1-4ba8-b106-b97439762b12)
