### ISSUE TITLE
after:content-['*']在小程序上通过不了

### ISSUE THREAD

**Issue by diff-c** [unocss-applet/unocss-applet#66]
`<view class="after:content-['*']"`，编译到小程序上会报错？
- unocss-applet版本：0.78

**Comment by diff-c** [comment]
`<view p18rpx>`，但是这样写在小程序上没有显示？

**Comment by Skiyee** [comment]
我这边是正常的，你再试试

**Comment by diff-c** [comment]
```js
    transformerAttributify({
      prefixedOnly: true, // 这里不写就会提示下方错误
      ignoreAttributes: ["block"]
    })
```
![image](https://github.com/unocss-applet/unocss-applet/assets/59114913/ff8d999e-161f-478e-b1cf-151c52675f3f)
这个是什么原因？

**Comment by diff-c** [comment]
写了编译到小程序就没有样式

**Comment by Skiyee** [comment]
请不要在一个 `issue` 内提出过多不同主题的问题

如果遇到新的问题，请重开一个 `issue` 并提供最小复现

PS: 该主题的issue已解决，我将关闭该issue

**Comment by diff-c** [comment]
这不是也是配置属性化吗？我写属性化方式，还是没显示类名呀

**Comment by Skiyee** [comment]
讨论已经偏离主题了哦

如果遇到新的问题需要重开一个新的issue，否则会导致其他参与者无法确定是在讨论什么问题，谢谢！
