### ISSUE TITLE
升级到0.8.2提示TypeError: (0 , _unocssApplet.transformerApplet) is not a function

### ISSUE THREAD

**Issue by wdzyy** [unocss-applet/unocss-applet#72]
![image](https://github.com/user-attachments/assets/26dfd119-a0e8-45b0-84c6-3e4ce73f3bb3)
![image](https://github.com/user-attachments/assets/70f8e1dc-01a5-4a1d-8f82-4a77d2e76ae2)

**Comment by Skiyee** [comment]
请参考文档使用，谢谢
https://github.com/unocss-applet/unocss-applet?tab=readme-ov-file#unocss-config

**Comment by wdzyy** [comment]
> 请参考文档使用，谢谢 https://github.com/unocss-applet/unocss-applet?tab=readme-ov-file#unocss-config

transformerApplet 这个方法是被去了是吧？看了文档，没有引入这个。
