### ISSUE TITLE
CLI integration transpiled pseudo class error when watch mode

### ISSUE THREAD

**Issue by chioio** [unocss-applet/unocss-applet#78]
```
first:bg-green-5   ->   first_a_bg-green-5
```
First build works, but cli mode must with `--write-transformed` parameter.
When source code transpiled to `first_a_bg-green-5`, unocss can't recognize when rerun watch mode, and removed `first_a_bg-green-5` in output css file.

**Comment by nei1ee** [comment]
This issue cannot be solved because the source code has been changed unless a set of adaptation rules is written.
