### ISSUE TITLE
Preset icons not work with `icon-sets:icon-name`

### ISSUE THREAD

**Issue by chioio** [unocss-applet/unocss-applet#79]
Like this `i-ant:design-home-twotone` not work, but `i-ant-design-home-twotone` works.

**Comment by nei1ee** [comment]
应该是 `i-ant-design:home-twotone`

**Comment by chioio** [comment]
对 `i-ant-design:home-twotone` 不生效，`i-ant-design-home-twotone` 才会生效

**Comment by nei1ee** [comment]
> 对 `i-ant-design:home-twotone` 不生效，`i-ant-design-home-twotone` 才会生效

试了下 `i-ant-design:home-twotone` 是没问题的，请提供复现。
