### ISSUE TITLE
The requested module '@unocss/preset-mini' does not provide an export named 'normalizePreflights'

### ISSUE THREAD

**Issue by lincenying** [unocss-applet/unocss-applet#84]
@unocss/preset-mini [v0.65.0](https://github.com/unocss/unocss/releases/tag/v0.65.0) 删除了`normalizePreflights`方法, 导致编译时报错

https://github.com/unocss-applet/unocss-applet/blob/main/packages/preset-applet/src/index.ts#L3

https://github.com/unocss-applet/unocss-applet/blob/main/packages/preset-applet/src/index.ts#L37

**Comment by bamf2077** [comment]
https://github.com/unocss/unocss/commit/882ce876391d0cb9be40fbb2328152537defdd00#diff-1172732bac2dec927cd2598b1acdb045ab1b10f346943ce5b9e12ff556726b30

大概是这么修改，未经测试

```diff
- import { normalizePreflights } from '@unocss/preset-mini'
+ import { preflights} from '@unocss/preset-mini'

- preflights: options.preflight
-   ? normalizePreflights(preflights, options.variablePrefix)
-   : [],
+ preflights: preflights(options),

**Comment by chioio** [comment]
更新没发版哦
